language: python
python:
  - "3.7"

sudo: required
services:
  - docker

before_install:
  - docker build -t likeclem30/recipeapi .
script:
  - docker images likeclem30/recipeapi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="likeclem30@gmail.com" -u="likeclem30" -p="Oracle_11g";
    docker push likeclem30/recipeAPI;
    fi
